### ISSUE TITLE
dns challenges error

### ISSUE THREAD

**Issue by MonoLogueChi** [caddy-dns/dnspod#4]
I download caddy from https://caddyserver.com/download     20210213

I found that the line is from the DNSPod management panel  _acme-challenge.domain.com ,It's not  _acme-challenge 。
I'm not familiar with go and don't know how to fix it.

**Comment by cubarco** [comment]
Same here.

**Comment by lscgzwd** [comment]
> I download caddy from https://caddyserver.com/download 20210213
> 
> I found that the line is from the DNSPod management panel _acme-challenge.domain.com ,It's not _acme-challenge 。
> I'm not familiar with go and don't know how to fix it.

Could you show me more detail ?
可以提供更详细的描述或者例子吗？没太理解。

**Comment by MonoLogueChi** [comment]
> > I download caddy from https://caddyserver.com/download 20210213
> > I found that the line is from the DNSPod management panel _acme-challenge.domain.com ,It's not _acme-challenge 。
> > I'm not familiar with go and don't know how to fix it.
> 
> Could you show me more detail ?
> 可以提供更详细的描述或者例子吗？没太理解。

目前遇到的问题是DNSPOD域名 主机记录为 `_acme-challenge.domain.com` 并不是 `_acme-challenge`，也就是完整的域名为  `_acme-challenge.domain.com.domain.com`

**Comment by lscgzwd** [comment]
> > > I download caddy from https://caddyserver.com/download 20210213
> > > I found that the line is from the DNSPod management panel _acme-challenge.domain.com ,It's not _acme-challenge 。
> > > I'm not familiar with go and don't know how to fix it.
> > 
> > 
> > Could you show me more detail ?
> > 可以提供更详细的描述或者例子吗？没太理解。
> 
> 目前遇到的问题是DNSPOD域名 主机记录为 `_acme-challenge.domain.com` 并不是 `_acme-challenge`，也就是完整的域名为 `_acme-challenge.domain.com.domain.com`

您说的这个问题是在另外一个项目中处理的，这个问题是处理过的，不知道是不是caddy官方打包的时候没用到最新的代码，你要不根据官方的教程，自己编译下试试？我们这边服务器上用的自己编译的版本是正常的。

这个是对应处理这个问题的函数
https://github.com/libdns/dnspod/blob/master/client.go
```
func extractRecordName(name string, zone string) string {
	if idx := strings.Index(name, "."+strings.Trim(zone, ".")); idx != -1 {
		return name[:idx]
	}
	return name
}
```

**Comment by lscgzwd** [comment]
> Same here.

this problem maybe fixed.
https://github.com/libdns/dnspod/blob/master/client.go
```
func extractRecordName(name string, zone string) string {
	if idx := strings.Index(name, "."+strings.Trim(zone, ".")); idx != -1 {
		return name[:idx]
	}
	return name
}
```
It maybe the caddy you  download from the caddy server site do not use the latest code.
Could you build it youself?

**Comment by lscgzwd** [comment]
I have released the newest code. Maybe the latest  build of caddy will been ok

**Comment by MonoLogueChi** [comment]
Has been used normally, thank you
